# This based on Decus CPP (1988-10-13), an almost-ANSI C preprocessor by
# Martin Minow, in the public domain. It has been shipped with X11R5
# (contrib/util/cpp). It contains some patches by pts for Minix
# compatibility.
#

cpp: cpp1.c cpp2.c cpp3.c cpp4.c cpp5.c cpp6.c cpp.h cppdef.h
	$(CC) -O -DOLD_PREPROCESSOR -DFILE_LOCAL=static -Dunix -DHOST=1 -DTARGET=0 -DMACHINE=\"i8088\" -DSYSTEM=\"minix\" -DCOMPILER=\"__STD_CC__\" -o cpp cpp1.c cpp2.c cpp3.c cpp4.c cpp5.c cpp6.c
	chmem =150000 cpp
